#!/bin/sh
sh script/is_safe || exit 1

compiler=$(sh script/key_single compiler)

dawning_flags=$(sh script/key dawning_flags)

$compiler $1.c -o $2 $dawning_flags $suppress

echo "Compiled $1.c to $2"
sh script/size $2

chmod +x $2