#!/bin/sh
source script/common

kernel_dir="linux"

flags_base=" -static -s -flto -nostdlib -nostartfiles -ffreestanding -fno-builtin"
flags_base="-fno-pic -fno-pie -mcmodel=kernel"

flags_base+=" -O2 -fomit-frame-pointer -fno-stack-protector"
flags_base+=" -Qn -Wl,--build-id=none"

#includes="-Ilinux/include"
#includes+=" -Ilinux/include/uapi"
#includes+=" -Ilinux/arch/x86/include"
#includes+=" -Ilinux/arch/x86/include/uapi"
#includes+=" -Ilinux/arch/x86/include/generated"

defines="-D__KERNEL__ -DMODULE -DKBUILD_MODNAME=\"$2\""

module_flags="-fno-common -DKBUILD_BASENAME=\"$2\" -fwhole-program"

output="-o $2.ko"

gcc $1 $output $flags_base $suppress $includes $defines $module_flags

echo "Compiled kernel module $1 to $2.ko"
sh script/size $2.ko

chmod +x $2.ko