#!/bin/sh

# Ensures that our assumptions about the script's execution location are correct
# to prevent rm -rf mishaps, or other unintended consequences.

safe_repo_name="dawning-linux"

current_dir=$(basename "$(pwd)")

if [ "$current_dir" != $safe_repo_name ]; then
    echo "ERROR: Not in repository root directory!"
    echo "This script must be run from the $safe_repo_name root directory."
    echo "Current directory: $(pwd)"
    exit 1
fi

exit 0