#!/bin/sh
source script/common

kernel_extract_dir="linux/" 
download_artifacts_dir="artifacts/"
keys_dir=$download_artifacts_dir"keys/"
trusted_keys="torvalds@kernel.org gregkh@kernel.org"
kernel_version="6.14.1"
kernel_download="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.14.1.tar.xz"
kernel_pgp="
-----BEGIN PGP SIGNATURE-----
Comment: This signature is for the .tar version of the archive
Comment: git archive --format tar --prefix=linux-6.14.1/ v6.14.1
Comment: git version 2.49.0

iQIzBAABCAAdFiEEZH8oZUiU471FcZm+ONu9yGCSaT4FAmfziMoACgkQONu9yGCS
aT7vCxAArowbafcC73ARYIBjkUnxXPScbAv/Xf5Vx7up9jiRFBqAAzOMGCD/tuah
DwwZ4YwqEFqYIC0loM+Dbuxt8TXTQuGqy+7wIExYleldK8LRnLfHIwNVgHOLoX2e
mD8pQslLP2KdkhGTDLT001Zdsp6H/Lwfmsn0YMSUj8eLAeCT7nrXwFkxPAJIaQkU
XYLxjw7Zg2fl0QbomRQPES3kS4hVz1KMzPR+UXUHn7/EuzCqgNoKb7rbr4IV3Kpo
4apJo9720oH9O8YaM6IWnvfdgzkxdaQczCx8rQL9052c6tt3LxltRNfzf/0MeSpM
TdZY8Lbka1HsEnEhx1zQ629MdtPNVGM/nq48Pr5J3EDyWZweoVv9zwdrkzD2cbBp
ZYJnGb8i9SubV2gG/xflcXpj8KxKhzGTettUrKVQ5JzbD/dYRLWyxyQl7fvp9kdd
Pnios3Z8sC3XPpOd6UvA7LpsnbtPxV4XzEAMQ6ozepaKK8dOOtsFqBSCojgvQhog
UzCgXEjcZAqm5rcgqkJHFsWUZ7bs8o0NhW4VfpCutCUpp7w9k1lpqm2RKneZs7Rb
R+EBEUMID4yoXJmR13G68jZY3NAvbLVO4JNhlB5fBIqJzfxRbBTaBFKKfbVLrVzo
g7kN4L+u19sKtotb1SaVodYcD6EFxHIoNS5dxiZ6jTq+cIwFS0o=
=iCQX
-----END PGP SIGNATURE-----
"

kernel_tarball=$download_artifacts_dir"linux-$kernel_version.tar"
kernel_archive=$kernel_tarball".xz"

if [ -d $kernel_extract_dir ]; then
    echo $BOLD "Kernel already extracted..." $RESET
    exit 0
fi

extract_kernel() {
    echo $BOLD "Checking kernel signature" $RESET
    gpg --locate-keys $trusted_keys

    unxz -k $kernel_archive

    echo "$kernel_pgp" > $kernel_tarball".sign"

    gpg --verify $kernel_tarball".sign" $kernel_tarball

    tar -xf $kernel_tarball --strip-components=1 -C $kernel_extract_dir

    rm $kernel_tarball

    echo $BOLD "Kernel extracted to $kernel_extract_dir" $RESET
}

is_file $kernel_archive || \
    curl -L $kernel_download -o $kernel_archive

mkdir -p $download_artifacts_dir
mkdir -p $kernel_extract_dir

extract_kernel
