#!/bin/sh
source script/common

kernel_extract_dir="linux/"
download_artifacts_dir="artifacts/"
keys_dir=$download_artifacts_dir"keys/"
trusted_keys="torvalds@kernel.org gregkh@kernel.org"
kernel_version="6.14.8"
kernel_download="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.14.8.tar.xz"
kernel_pgp="
-----BEGIN PGP SIGNATURE-----
Comment: This signature is for the .tar version of the archive
Comment: git archive --format tar --prefix=linux-6.14.8/ v6.14.8
Comment: git version 2.49.0

iQIzBAABCAAdFiEEZH8oZUiU471FcZm+ONu9yGCSaT4FAmgvGiQACgkQONu9yGCS
aT6IQBAAkt7T95aE8SQ33KJi33pqszezth4N/7H83+pu9RazHArTAEILczp/S0I1
hgLgCQ6McoRVHS+PBqEHXJ3+13wDD41bFb5G5su/b/h3xmdvBHjXA0IESjFt23iW
WXGgd0L71IhNqsRTrSeSZUMAG/VbO9f6+yiGBcJmhUv/1lIExYzYfyQDOC9ND2zB
nIR39bV9nPruHAr4LlSaF/h+lVuRPoDblhqLiRk0pkY7paZqPFYSEsTSvLhl0xzB
r2V2X219yM6LcHtIQ0bU+MC2/PFtohNZ3S3Whq2XSejmqV7vhg8diu8caOSeARPx
qawfJLFivouicsVKOefW4iS/2oaBfikW3pHXVJw6lUIzN+N7+iIcijLISvqqx0/R
+Q5sXj2vP7oo3pKmzaP43HlNkdn4FhAyuN0vB9NIrBTZxicBpgphhtrTo3H3XWJm
rXtA262k1XPSbpByeftn6t6ePPIwV8gyZOvxaZ8RKcxASgbflPmR85SpmOWLTUMB
V7HG+8W13Ln1rvMI5ALThvdaD7pzejdQsl/ScHFK+0Ac3BP+C00hAoUHj6m5maPu
EcGRNG9H9Pj+2taouw5GQaZJs1TL0l+2mBivyKAKJ6XPezSFPqeY3Hg/VZaV5QJb
XOgeBrP6yZlhYgkeOtBckAmpfUvT9FrcKRjuD/W5q01KY6LQzeU=
=455m
-----END PGP SIGNATURE-----
"

kernel_tarball=$download_artifacts_dir"linux-$kernel_version.tar"
kernel_archive=$kernel_tarball".xz"

if [ -d $kernel_extract_dir ]; then
    echo $BOLD "Kernel already extracted..." $RESET
    exit 0
fi

extract_kernel() {
    echo $BOLD "Checking kernel signature" $RESET
    gpg --locate-keys $trusted_keys

    unxz -k $kernel_archive

    echo "$kernel_pgp" >$kernel_tarball".sign"

    gpg --verify $kernel_tarball".sign" $kernel_tarball

    tar -xf $kernel_tarball --strip-components=1 -C $kernel_extract_dir

    rm $kernel_tarball

    echo $BOLD "Kernel extracted to $kernel_extract_dir" $RESET
}

is_file $kernel_archive ||
    curl -L $kernel_download -o $kernel_archive

mkdir -p $download_artifacts_dir
mkdir -p $kernel_extract_dir

extract_kernel
