#!/bin/sh

color_green="\033[0;32m"
color_red="\033[0;31m"
color_yellow="\033[0;33m"
color_blue="\033[0;34m"
color_purple="\033[0;35m"
color_cyan="\033[0;36m"
color_white="\033[0;37m"
color_reset="\033[0m"
color_bold="\033[1m"

e=""
if [ "$(uname)" = "Linux" ]; then
    e="-e "
fi

echo $e $color_cyan $color_bold
echo $e "    $@"
echo $e "_____________________________________________________________________________"
echo $e $color_reset