#!/bin/sh

ANSI=$'\033['

RESET=$ANSI"0m"
BOLD=$ANSI"1m"

RED=$ANSI"91m"
GREEN=$ANSI"92m"
YELLOW=$ANSI"93m"
BLUE=$ANSI"94m"
MAGENTA=$ANSI"95m"
CYAN=$ANSI"96m"
WHITE=$ANSI"97m"

echo $CYAN $BOLD
echo "    $@"
echo "_____________________________________________________________________________"
echo $RESET