#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then
    size=$(stat -f %z "$1")
else
    size=$(stat -c %s "$1")
fi

echo "$size bytes ($(echo "scale=2; $size / 1024" | bc) KB, $(echo "scale=2; $size / 1024 / 1024" | bc) MB)"